### ISSUE TITLE
The layout is breaking down, how to disable range without mouse clicking?

### ISSUE THREAD

**Issue by GermanAizek** [ART3MISTICAL/cpu-controller#2]
@devansharora18, how to disabled range (from - to).
I'm tired clicking on only one configuration, there is a configuration with 256 threads-cores.
![изображение](https://github.com/user-attachments/assets/d37c4ff1-6a74-4f82-8c0e-0430aa83a478)

**Comment by devansharora18** [comment]
will fix it in a few days (exams are going on rn)

**Comment by GermanAizek** [comment]
> will fix it in a few days (exams are going on rn)

Many thanks!
